unit-config: &unit-config
  steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "composer.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run: composer install -n --prefer-dist

    - save_cache:
        paths:
          - ./vendor
        key: v1-dependencies-{{ checksum "composer.json" }}

    # run tests!
    - run: vendor/bin/phpcs --standard=./phpcs-ruleset.xml
    - run: vendor/bin/phpunit

version: 2
jobs:
  php56:
    <<: *unit-config
    docker:
      - image: circleci/php:5.6-node

  php70:
    <<: *unit-config
    docker:
      - image: circleci/php:7.0-node

  php71:
    <<: *unit-config
    docker:
      - image: circleci/php:7.1-node

  php72:
    <<: *unit-config
    docker:
      - image: circleci/php:7.2-node

workflows:
  version: 2
  units:
    jobs:
      - php56
      - php70
      - php71
      - php72
